/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerMenu;
import Model.Usuario;
import java.awt.Color;

/**
 *
 * @author Daniel Barroso de Oliveira | Email: unfidoliveira@fei.edu.br 
 */
public class FrameMenu extends javax.swing.JFrame {

    private final ControllerMenu controlador;
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu(Usuario user) {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#f0fbff"));
        controlador = new ControllerMenu(this, user);
        TxtNome.setText(user.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAcessaPLaylist1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtOla = new javax.swing.JLabel();
        TxtNome = new javax.swing.JLabel();
        BtAcessaPLaylist2 = new javax.swing.JButton();
        BtAcessaCurtidas = new javax.swing.JButton();
        BtAcessaPLaylist = new javax.swing.JButton();
        BtAcessaMusicas = new javax.swing.JButton();

        BtAcessaPLaylist1.setText("Minhas Playlists");
        BtAcessaPLaylist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaPLaylist1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 255, 254));

        jPanel1.setBackground(new java.awt.Color(20, 133, 209));

        TxtOla.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        TxtOla.setForeground(new java.awt.Color(218, 255, 254));
        TxtOla.setText("Olá,");

        TxtNome.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        TxtNome.setForeground(new java.awt.Color(218, 255, 254));
        TxtNome.setText("Nome");

        BtAcessaPLaylist2.setBackground(new java.awt.Color(20, 133, 209));
        BtAcessaPLaylist2.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaPLaylist2.setForeground(new java.awt.Color(188, 255, 254));
        BtAcessaPLaylist2.setText("Sair");
        BtAcessaPLaylist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaPLaylist2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TxtOla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtAcessaPLaylist2)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtOla)
                        .addComponent(TxtNome))
                    .addComponent(BtAcessaPLaylist2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BtAcessaCurtidas.setBackground(new java.awt.Color(188, 255, 254));
        BtAcessaCurtidas.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaCurtidas.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaCurtidas.setText("Minhas Curtidas");
        BtAcessaCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaCurtidasActionPerformed(evt);
            }
        });

        BtAcessaPLaylist.setBackground(new java.awt.Color(185, 254, 255));
        BtAcessaPLaylist.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaPLaylist.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaPLaylist.setText("Minhas Playlists");
        BtAcessaPLaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaPLaylistActionPerformed(evt);
            }
        });

        BtAcessaMusicas.setBackground(new java.awt.Color(188, 255, 254));
        BtAcessaMusicas.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaMusicas.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaMusicas.setText("Músicas");
        BtAcessaMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaMusicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtAcessaMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAcessaCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAcessaPLaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAcessaCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAcessaPLaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAcessaMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(391, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAcessaPLaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaPLaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaPLaylistActionPerformed

    private void BtAcessaPLaylist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaPLaylist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaPLaylist1ActionPerformed

    private void BtAcessaCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaCurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaCurtidasActionPerformed

    private void BtAcessaPLaylist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaPLaylist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaPLaylist2ActionPerformed

    private void BtAcessaMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaMusicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaMusicasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAcessaCurtidas;
    private javax.swing.JButton BtAcessaMusicas;
    private javax.swing.JButton BtAcessaPLaylist;
    private javax.swing.JButton BtAcessaPLaylist1;
    private javax.swing.JButton BtAcessaPLaylist2;
    private javax.swing.JLabel TxtNome;
    private javax.swing.JLabel TxtOla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
