/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCadastro;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Daniel Barroso de Oliveira | Email: unfidoliveira@fei.edu.br 
 */
public class FrameCadastro extends javax.swing.JFrame {

    private final ControllerCadastro controlador;

    /**
     * Creates new form FrameLogin
     */
    public FrameCadastro() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#f0fbff"));
        controlador = new ControllerCadastro(this);
    }

    public JButton getBtLogin1() {
        return BtCadastrarUsuario;
    }

    public JButton getBtVoltaParaLogin() {
        return BtVoltaParaLogin;
    }

    public JTextField getCampoNome() {
        return CampoNome;
    }

    public JTextField getCampoSenha() {
        return CampoSenha;
    }

    public JTextField getCampoUsuario() {
        return CampoUsuario;
    }

    public JLabel getLabelSenha() {
        return LabelSenha;
    }

    public JLabel getLabelUsuario() {
        return LabelUsuario;
    }

    public JLabel getLabelUsuario1() {
        return LabelUsuario1;
    }

    public JLabel getTxtSpotfei1() {
        return TxtSpotfei1;
    }

    public JLabel getTxtSpotfei2() {
        return TxtSpotfei2;
    }

    public JLabel getTxtSpotfei3() {
        return TxtSpotfei3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setBtLogin1(JButton BtLogin1) {
        this.BtCadastrarUsuario = BtLogin1;
    }

    public void setBtVoltaParaLogin(JButton BtVoltaParaLogin) {
        this.BtVoltaParaLogin = BtVoltaParaLogin;
    }

    public void setCampoNome(JTextField CampoNome) {
        this.CampoNome = CampoNome;
    }

    public void setCampoSenha(JTextField CampoSenha) {
        this.CampoSenha = CampoSenha;
    }

    public void setCampoUsuario(JTextField CampoUsuario) {
        this.CampoUsuario = CampoUsuario;
    }

    public void setLabelSenha(JLabel LabelSenha) {
        this.LabelSenha = LabelSenha;
    }

    public void setLabelUsuario(JLabel LabelUsuario) {
        this.LabelUsuario = LabelUsuario;
    }

    public void setLabelUsuario1(JLabel LabelUsuario1) {
        this.LabelUsuario1 = LabelUsuario1;
    }

    public void setTxtSpotfei1(JLabel TxtSpotfei1) {
        this.TxtSpotfei1 = TxtSpotfei1;
    }

    public void setTxtSpotfei2(JLabel TxtSpotfei2) {
        this.TxtSpotfei2 = TxtSpotfei2;
    }

    public void setTxtSpotfei3(JLabel TxtSpotfei3) {
        this.TxtSpotfei3 = TxtSpotfei3;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtSpotfei2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtSpotfei1 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        LabelSenha = new javax.swing.JLabel();
        CampoSenha = new javax.swing.JTextField();
        BtVoltaParaLogin = new javax.swing.JButton();
        BtCadastrarUsuario = new javax.swing.JButton();
        TxtSpotfei3 = new javax.swing.JLabel();
        LabelUsuario1 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(218, 255, 254));

        TxtSpotfei2.setFont(new java.awt.Font("Ebrima", 1, 55)); // NOI18N
        TxtSpotfei2.setForeground(new java.awt.Color(0, 80, 122));
        TxtSpotfei2.setText("SPOT");
        TxtSpotfei2.setInheritsPopupMenu(false);

        jPanel1.setBackground(new java.awt.Color(20, 133, 209));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TxtSpotfei1.setFont(new java.awt.Font("Ebrima", 1, 55)); // NOI18N
        TxtSpotfei1.setForeground(new java.awt.Color(20, 133, 209));
        TxtSpotfei1.setText("FEI");
        TxtSpotfei1.setIconTextGap(0);
        TxtSpotfei1.setInheritsPopupMenu(false);

        LabelUsuario.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        LabelUsuario.setText("Usuário");

        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });

        LabelSenha.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        LabelSenha.setText("Senha");

        CampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaActionPerformed(evt);
            }
        });

        BtVoltaParaLogin.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtVoltaParaLogin.setForeground(new java.awt.Color(0, 80, 122));
        BtVoltaParaLogin.setText("«");
        BtVoltaParaLogin.setToolTipText("");
        BtVoltaParaLogin.setMargin(new java.awt.Insets(-8, 14, 3, 14));
        BtVoltaParaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltaParaLoginActionPerformed(evt);
            }
        });

        BtCadastrarUsuario.setBackground(new java.awt.Color(20, 133, 209));
        BtCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtCadastrarUsuario.setForeground(new java.awt.Color(245, 248, 250));
        BtCadastrarUsuario.setText("Cadastrar");
        BtCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarUsuarioActionPerformed(evt);
            }
        });

        TxtSpotfei3.setFont(new java.awt.Font("Ebrima", 0, 26)); // NOI18N
        TxtSpotfei3.setForeground(new java.awt.Color(0, 80, 122));
        TxtSpotfei3.setText("Cadastro");
        TxtSpotfei3.setInheritsPopupMenu(false);

        LabelUsuario1.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        LabelUsuario1.setText("Nome");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtSpotfei2)
                        .addGap(0, 0, 0)
                        .addComponent(TxtSpotfei1))
                    .addComponent(LabelUsuario)
                    .addComponent(CampoUsuario)
                    .addComponent(LabelSenha)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(BtVoltaParaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtSpotfei3)
                    .addComponent(LabelUsuario1)
                    .addComponent(CampoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSpotfei2)
                    .addComponent(TxtSpotfei1))
                .addGap(1, 1, 1)
                .addComponent(TxtSpotfei3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuario)
                .addGap(0, 0, 0)
                .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuario1)
                .addGap(0, 0, 0)
                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSenha)
                .addGap(0, 0, 0)
                .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtVoltaParaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    private void CampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenhaActionPerformed

    private void BtCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarUsuarioActionPerformed
        controlador.SalvarCadastro();
    }//GEN-LAST:event_BtCadastrarUsuarioActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void BtVoltaParaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltaParaLoginActionPerformed
        FrameLogin login_janela = new FrameLogin();
        login_janela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtVoltaParaLoginActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex)BtVoltaParaLogin   } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameCadastro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrarUsuario;
    private javax.swing.JButton BtVoltaParaLogin;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoSenha;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel LabelUsuario1;
    private javax.swing.JLabel TxtSpotfei1;
    private javax.swing.JLabel TxtSpotfei2;
    private javax.swing.JLabel TxtSpotfei3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
