/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ControllerPerfil;
import Model.Usuario;
import java.awt.Color;
/**
 *
 * @author Daniel Barroso de Oliveira | Email: unfidoliveira@fei.edu.br
 */
public class FramePerfilUsuario extends javax.swing.JFrame {

    private final ControllerPerfil controlador;
    /**
     * Creates new form FramePerfilUsuario
     */
    public FramePerfilUsuario(Usuario user) {
        initComponents();
        controlador = new ControllerPerfil(this, user);
        this.getContentPane().setBackground(Color.decode("#f0fbff"));
        TxtNome.setText(user.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAcessaCurtidas = new javax.swing.JButton();
        BtAcessaPlaylist = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtOla = new javax.swing.JLabel();
        TxtNome = new javax.swing.JLabel();
        BtSair = new javax.swing.JButton();
        BtVoltaMenu = new javax.swing.JButton();
        BtAcessaDescurtidas = new javax.swing.JButton();
        BtAcessaRemovidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtAcessaCurtidas.setBackground(new java.awt.Color(188, 255, 254));
        BtAcessaCurtidas.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaCurtidas.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaCurtidas.setText("Curtidas");
        BtAcessaCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaCurtidasActionPerformed(evt);
            }
        });

        BtAcessaPlaylist.setBackground(new java.awt.Color(185, 254, 255));
        BtAcessaPlaylist.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaPlaylist.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaPlaylist.setText("Minhas Playlists");
        BtAcessaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaPlaylistActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 133, 209));

        TxtOla.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        TxtOla.setForeground(new java.awt.Color(218, 255, 254));
        TxtOla.setText("Olá,");

        TxtNome.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        TxtNome.setForeground(new java.awt.Color(218, 255, 254));
        TxtNome.setText("Nome");

        BtSair.setBackground(new java.awt.Color(20, 133, 209));
        BtSair.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtSair.setForeground(new java.awt.Color(188, 255, 254));
        BtSair.setText("Sair");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        BtVoltaMenu.setBackground(new java.awt.Color(20, 133, 209));
        BtVoltaMenu.setFont(new java.awt.Font("Ebrima", 1, 40)); // NOI18N
        BtVoltaMenu.setForeground(new java.awt.Color(188, 255, 254));
        BtVoltaMenu.setText("«");
        BtVoltaMenu.setMargin(new java.awt.Insets(-5, 14, 3, 14));
        BtVoltaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TxtOla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtVoltaMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtVoltaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtOla)
                                .addComponent(TxtNome)))))
                .addContainerGap())
        );

        BtAcessaDescurtidas.setBackground(new java.awt.Color(188, 255, 254));
        BtAcessaDescurtidas.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaDescurtidas.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaDescurtidas.setText("Descurtidas");
        BtAcessaDescurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaDescurtidasActionPerformed(evt);
            }
        });

        BtAcessaRemovidas.setBackground(new java.awt.Color(185, 254, 255));
        BtAcessaRemovidas.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        BtAcessaRemovidas.setForeground(new java.awt.Color(20, 133, 209));
        BtAcessaRemovidas.setText("Removidas");
        BtAcessaRemovidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAcessaRemovidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtAcessaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAcessaCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAcessaDescurtidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAcessaRemovidas)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAcessaCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAcessaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAcessaDescurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAcessaRemovidas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAcessaCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaCurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaCurtidasActionPerformed

    private void BtAcessaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaPlaylistActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtAcessaDescurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaDescurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaDescurtidasActionPerformed

    private void BtAcessaRemovidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAcessaRemovidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAcessaRemovidasActionPerformed

    private void BtVoltaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltaMenuActionPerformed
        FrameMenu menu_janela = new FrameMenu(controlador.getUser());
        menu_janela.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BtVoltaMenuActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FramePerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FramePerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FramePerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FramePerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FramePerfilUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAcessaCurtidas;
    private javax.swing.JButton BtAcessaDescurtidas;
    private javax.swing.JButton BtAcessaPlaylist;
    private javax.swing.JButton BtAcessaRemovidas;
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtVoltaMenu;
    private javax.swing.JLabel TxtNome;
    private javax.swing.JLabel TxtOla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
